// Smoke test for the patched official workspace client bundle
// (lib/client.js, generated by lib/build.mjs): executes it in Node with a
// real DSH module loader and service stubs so cold-load dependency errors
// are caught before the browser loads it. Rendering happens inside the slot
// framework, so apply only needs locale/slots/workspaces/sessions stubs.
import assert from "node:assert/strict"
import { createRequire } from "node:module"
import { existsSync, globSync, readFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, join } from "node:path"
import { homedir } from "node:os"

const profileRequire = createRequire(join(homedir(), ".dsh", "profiles", "web", "package.json"))
const React = profileRequire("react")
const jsxRuntime = profileRequire("react/jsx-runtime")
const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const packageJson = JSON.parse(readFileSync(join(root, "package.json"), "utf8"))

// Like the build, use an installed DSH bundle rather than reimplementing its
// loader in the test. An explicit path allows checking a different host version.
const loaderPath = process.env.DSH_CLIENT_MODULES_BUNDLE || [
  "/Applications/DSH Desktop.app/Contents/Resources/app.asar.unpacked/node_modules/@deepseek-ai/dsh-client-modules/lib/client.js",
  join(homedir(), ".dsh", "profiles", "web", "node_modules", "@deepseek-ai", "dsh-client-modules", "lib", "client.js"),
  ...globSync(join(homedir(), ".npm", "_npx", "*", "node_modules", "@deepseek-ai", "dsh-client-modules", "lib", "client.js")),
].find((path) => existsSync(path))
if (!loaderPath) throw new Error("cannot locate DSH client module loader; set DSH_CLIENT_MODULES_BUNDLE")
let loaderRegistration
new Function("window", readFileSync(loaderPath, "utf8"))({
  __ModuleLoader__: { load: (registration) => { loaderRegistration = registration } },
})
const loaderExports = loaderRegistration.factory((name) => {
  throw new Error("unexpected loader bootstrap require: " + name)
})
const { ClientModuleSystem, parseBootManifest } = loaderExports

let factory
const fakeWindow = {
  __ModuleLoader__: {
    load: ({ id, factory: f }) => {
      if (id !== "dsh-worktree-panel") throw new Error("unexpected bundle id: " + id)
      factory = f
    },
  },
}

const code = readFileSync(join(root, "lib", "client.js"), "utf8")
if (!code.includes('id: "initialize-git"')) throw new Error("non-git initialize action missing from project menu")
if (!code.includes("startSession(group.workspaceId);")) throw new Error("non-git plus button does not start a session directly")
if (code.includes('type: "new"')) throw new Error("legacy non-git choice dialog is still reachable")
// The bundle touches document only inside __wtpEnsureCss (called from a
// component hook) and the CSS module injector, which is guarded by
// `typeof document !== "undefined"`; render paths are not exercised here.
new Function("window", code)(fakeWindow)

if (!factory) throw new Error("bundle did not register a factory")

const primitivesStub = new Proxy(
  {},
  {
    get: (target, prop) => {
      if (prop === Symbol.toStringTag) return "Module"
      // Components reference icons/primitives lazily at render time only.
      return (...args) => (typeof args[0] === "string" ? args[0] : "stub")
    },
  },
)

const runtimeId = "@deepseek-ai/dsh-client-runtime"
const primitivesId = "@deepseek-ai/dsh-client-ui-primitives"
const factories = new Map([
  [packageJson.name, factory],
  [runtimeId, () => ({
    defineStore: (spec) => ({ ...spec }),
    abbreviateHomePath: (path, home) => home && path.startsWith(home) ? "~" + path.slice(home.length) : path,
  })],
  [primitivesId, () => primitivesStub],
])

async function coldImport(external) {
  const loaded = []
  const manifest = parseBootManifest({
    rev: "test",
    entries: [...factories.keys()].map((id) => ({
      id, url: id, rev: "test",
      ...(id === packageJson.name ? { ...packageJson.dsh.client, external } : {}),
    })),
  })
  const loader = new ClientModuleSystem({
    manifest,
    staticModules: { react: React, "react/jsx-runtime": jsxRuntime },
    bootstrapModule: { id: loaderRegistration.id, exports: loaderExports },
    registrationTarget: { mode: "queue", pendingQueue: [] },
    loadBundle: async (id) => {
      assert.ok(factories.has(id), "unexpected bundle: " + id)
      loaded.push(id)
      loader.register({ id, factory: factories.get(id) })
    },
  })
  return { mod: await loader.import(packageJson.name), loaded }
}

// Neither injected services nor platform-provided React should accidentally
// warm the runtime/primitives cache and mask missing dynamic dependencies.
await assert.rejects(coldImport(undefined), /require\("@deepseek-ai\/dsh-client-runtime\/client"\) missed the module table/)
await assert.rejects(coldImport([runtimeId + "/client"]), /require\("@deepseek-ai\/dsh-client-ui-primitives"\) missed the module table/)
const { mod, loaded } = await coldImport(packageJson.dsh.client.external)
assert.equal(loaded.at(-1), packageJson.name, "dependencies must arrive before the plugin")
assert.deepEqual(new Set(loaded), new Set([runtimeId, primitivesId, packageJson.name]))

if (typeof mod.apply !== "function") throw new Error("client bundle exports no apply")
if (!Array.isArray(mod.inject)) throw new Error("client bundle exports no inject list")
if (!mod.inject.includes("connection")) throw new Error("client bundle does not inject connection")

const registrations = []
const hostDescription = {
  getSnapshot: () => ({ home: "/Users/you" }),
  subscribe: () => () => {},
}
const ctx = {
  get: (name) => name === "connection" ? { hostDescription } : undefined,
  locale: {
    register: () => {},
    bind: (ns) => (key, vars) => key,
  },
  sessions: {
    search: async () => ({ ok: true, value: { items: [] } }),
    searchResultLimit: 50,
    binding: () => undefined,
    fork: async () => "child",
    open: () => {},
  },
  workspaces: {
    startSession: () => {},
    rename: async () => {},
    delete: async () => {},
    insertBefore: async () => {},
    archiveSession: async () => {},
    insertSessionBefore: async () => {},
    create: async () => ({}),
  },
  slots: {
    entries: () => [],
    subscribe: () => () => {},
    inject: (name, cb) => {
      registrations.push({ name, registered: cb() })
    },
    register: (opts, Component) => ({ opts, Component }),
  },
  effect: (fn) => {
    const dispose = fn()
    return () => {
      try {
        dispose?.()
      } catch {
        /* ignore */
      }
    }
  },
}

mod.apply(ctx) // official apply registers effects/slots via ctx; returns undefined by design

const slotNames = registrations.map((r) => r.name).join(",")
if (!slotNames.includes("sidebar.workspaces")) throw new Error("sidebar.workspaces slot not registered")
if (!slotNames.includes("conversation.hero.workspace")) throw new Error("hero workspace slot not registered")
if (!slotNames.includes("settings.section")) throw new Error("settings.section slot not registered")

console.log(
  "client smoke test OK: real DSH loader cold-imported the bundle, apply registered slots [" + slotNames + "]",
)
